# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Joabe de Souza Santos
email: joabeo@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  "Systems Specialist with over 12 years of experience in system analysis and development. 
  Expert in Java programming language and frameworks such as Spring, JSF, Primefaces, and JPA. 
  Strong background in API development, system integration, as well as skills in data modeling, 
  requirements gathering, and the use of DevOps tools. Familiar with agile methodologies (Scrum) 
  and modern technologies such as Kafka, React.js with TypeScript, and Multi-Cloud. 
  Holds a Bachelor's degree in Computer Science from Universidade São Judas Tadeu."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  joabss

markdown: kramdown

permalink: none
comments: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Joabe Souza"
      category: "jekyll"